name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: 188.166.255.175
          username: coba
          password: multipolar123
          script: |
            cd /home/nobuservice/cicdtest
            mvn clean install        
            
      - name: Push to server1
        uses: appleboy/ssh-action@master
        with:
          host: 188.166.255.175
          username: coba
          password: multipolar123
          script: |
            cd /home/nobuservice/cicdtest
            mvn install
            docker build -t nobuservicebygithubaction .
            
      - name: Push to server1
        uses: appleboy/ssh-action@master
        with:
          host: 188.166.255.175
          username: coba
          password: multipolar123
          script: |
            cd /home/nobuservice/cicdtest            
            docker run -d --name nobuserviceindomaret --net=host --restart=always -p 8101:8101 registry.gitlab.com/erid.rahmad/nobu
    
