# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: MIIJKgIBAAKCAgEAwumNo5FC5kXH5a+LpAYnHErJev1l9M/LmWdNQEFKZRlskjVZ
Fon7WYk6UY/2NpIdW7V9hKcCBjbMdJZU6GTxehnfz7N29fxdXWW1TKha2rGzcu/R
lOcWmdhgy5n0uDFZq8eEakX2NedCoycR0EoAl7BsAmKJL8X6M+xJNRcSM29FZGVw
rqHpvx7Dg7D4wiv2js6tIj9PcaMhdKuuVVqHEww5e5r2o95vCgnSH9DpMEKm/mX6
i/z4lNh0dfbXCpzqLQluOm39StDwPERBS0uA6igzB8l0hlPNrgSqdRLE1FQjYCZ1
EtNjteeJfSxCBrqUqMSXtAGuq+NEfDzm/MrKzrfJCmRBznKZCcLE9kZsPh4AUecd
FTykB1zvVwAM1jitES6xBpSWjZg4WkX7fV9WDAL7uHGkWEDQq8eo4sfsPOogHdh0
r+qc933AsK0IjHxr1/Zp3NJLPhRNw9OvH1v2KsOs6RbrxgMxdUWxTJ0Eokm4zusy
ykwRwwnqkiAnYsgZnHO2I3K7ENcgIwPD7uksoLEPRDxJ4VZgDPiwU4TpcMREIy2Z
4l4frkHTC157lF8RSB1vLA69gDWZJvHup99WoRb11K3p/JpBa8y11w8fUyWqf5RW
NlAqkU0OrvMutTsrksP7ZuMjLIpUkgaxWOk7hVUqQ1YeYwpkOYTJBCZU3SMCAwEA
AQKCAgEAqI5XCaOeSgsAgpXb2b3kZqgaMv0eBacJeCEIgk+0KVfiN1JhN4ed0OFG
iLBJiQm0z9FUubm/m2YaS5yR0uMwnJnxnemiL7nNd+5z6dYRs9xGxle0U+O//M1N
b+U053DuDgqdbVYRRK44R2WLFyhX+NX9odZasvCvneVxrbLE76wDQ34iAzNMNBZD
mAgcJ7bjIr6CpQJBDpG3ZfDt8yw1cXh54XWyYyYBupmhmBgPAMgzJ/9Cu3rJ8dZ6
aGVNtATc0pO8OlVR3Thw+H1CRf4GfvjCoLJLzbp9PUcVrebMRp54dTbsuZoLOY0A
rjnu42jJFGXmlyl5R3ZjjFkSnHw3AybdmEn2lxRjIDYSu3HMLhgTvh1t6Z2vErDM
+kCWh0DkjlMs+j7dLButnPf87r5cd49iEXb5A2Qrf43moKnRtMY7vkIqeCa7saln
FoKdtRxI8amzuYZe/G2b0EEWD5SD7wZFIlovUVfctFcQh8PfypixAzRnvsKkIvGE
H0cLuXjCTuexUXWsl5Rj2g4wybff3Jfvw+lMX+9QJLWU4AByjMi5mAGTGTYglTIb
Bxrzg9bWQCdcF6EWWvg1zz3pUGuP+ookXVOBMBZnK+omzPrNdoyic8bAZiJhJCm9
HpEvtSq8Cba5BxqfFO9zTFcunh2TeIrtAvSqFsuHPXVuNGlrygECggEBAPmKB1Eq
CT/aENFAKqtV00igv7F1gT9aV897Jzte5c/JJPFrhcYGn/B/dfeBkUOH/Okxqzh8
o4slZBk7KnBmoicthhh4yRb3mdnCBJDAOOQRCPggKHyzG+D/Subl0xoe6fRikIsS
1loFgyoHYnGlD1ExCFMpEFR09PYqFqlXa8Icu0dRuIex/5N3f9bIRM4PUIlLKp74
9/K3ucZukRmeCVMnf9LfSjjL5heGOn5P8Y0ga1+uKodM/T5qksWIHD1q0p0JvtCr
Gk8Zidk5eB8/+Lvc4Ay7Lro0MsM6cnlUqGdo04qcU2ge7RCXa4jhgcRNKHQTNUeW
grH3a+ifDIx9JwECggEBAMf1c8Z58TURGPajAKjvDou8+0F5tToo/FG6L6Atv3LA
czCfYVMAtofUPmZKTQvXSHQbptGNKisewgbMS0ueM4tRktvDwQ8whMjKkb3eGO24
jwxIxwVLJszv4yoyoqtCp9GPziPU8f7LnZr64L2brxm0cdXZPrJwngJNb4eMOv4l
tvGylC5HjeInOCVHHddxZi5Zo9V6m11FKLcgNGUKYYzqrU33ypcn+rBohIL7d8WK
lZLKsxBRVKHe5a3b+yFZEUARsjqufvU7igIuTHkuptg/efO22amh8cZGJzVp6O7p
UMIC48hkRHgLP/uuq71c8nGc6WX9BthrBy4x6vSAiCMCggEAJf/69UUte2e9v9/B
n63GKv0vs9ptADTFwnbClqvw2x+KXKk/CdTgbkM6t6IneN0wimJh7Iwua3YaNC1q
XQuEDetEzF04YiL6bsq430ImZ7SgZQigoby0tiKqSVceOpASmICZ+lO4CKVmP/Q3
7Y5xMrAA0IkkT3gwBXyLTuZdJoYxjr7HFwLoJJDCCvccYzS50u57YxIO0AtiYvFb
b0c9rEgLkxUlvFhwhYyPQ8Twx8j0EPH4z/nNZr/b8fC0PDYUNI3TXPtxWjJNZ6L0
w+199z2/cLDggMKKKGiyHf/iVT0FWcpMeUKcXzZvzbxpgnctfd+e8XPeGzPOXvI5
evtkAQKCAQEAtWiA1cMRy0Qssq2lTp47Qxl7laZWfWJrr7XLuXVnqDLjDmy6PjR6
ZPZwehrUlXaF3BiuGpUIecBY5RP5B6yKNM4X/1s0TpSFEyl8WZYiZaE33jw0mx/Y
HrtQC5uOqvM5D015BlcOCUwvO0h6Fmsky5xCXnHOiNLU91/LXF0jtCkBNXv/JZFz
LobIUEGZ2DigLFLU6TtnspGo46LLBhQJ9m9+NSsmWEZEEEFyXubHfadCFb/h/l7a
+lQfacEWr+V/WfH0EXr34YJXrazVYmeppKzJ9gqgpF4w2+IPdk0Ur5Nq2ekHQGl/
GK2UKcEJPC4UInDp6sZIrJVFGWreL15gowKCAQEA5iZEPCr4FLkMJ4kGR/hC+75t
OoFRevAC+1yXvuR1On+2QMZ5kcG3wja5j5GR88rZYN9m36+fUU/3AFmFYV8WYZgf
oF3IrkpcEcrquDcKCNBzcCnWKeuP2FXGdzBdM4iPfWcZmEE50Sfmjctt7ca18Gqc
P9IsyUTORfDSW4sH5W6jBsyoT3smVc1Ds0AGI61I8uatUEZZUBWGDGWqsaUTuGM3
xg1w+mUcpbrMxjPxZayQyLrqzme102OcGv/9jjb8PXCYFgMvYnzF1/KtL99dDBD5
eSSUbQbKbOHoj1NxPg1JrUZobue58dZxUC+5EY9ryOgLM2etm7EJ+XmhGmDKsw==
          ARGS: "-rltgoDzvO"
#           SOURCE: "dist/"
          REMOTE_HOST: 188.166.255.175
          REMOTE_USER: root
          TARGET: /root
          port: 22 
          scrip: |
            java
            


